### ISSUE TITLE
Getting StaleElementReferenceException

### ISSUE THREAD

**Issue by bbashy** [roquie/laravel-dusk-select2#1]
Hi,

I'm getting;
```
Facebook\WebDriver\Exception\StaleElementReferenceException:
stale element reference: element is not attached to the page document
```
when running a simple select2 without AJAX.
```
->select2('.selectify + .select2', (string) $randomClient->name)
```
It does select it though, which is weird

![](https://d.pr/i/JVtDW/4hEF8SsA.jpg)

Can you see anything wrong?

**Comment by roquie** [comment]
Hi,

> Can you see anything wrong?

Nope.

Can try run without second parameter:
```
->select2('.selectify + .select2')
```

Error is gone? If not, you can run javascript commands in manual mode (in sequence) to find error execution. I see you use the custom styles or some plugin that may be to affect selection process.

**Comment by roquie** [comment]
Stack trace will be useful for me (of course, your can to overwrite private information).

**Comment by bbashy** [comment]
Thanks for replying. Opted for just sticking with a normal ->type() for it. Don't really have time to debug something that isn't that important right now :P

**Comment by roquie** [comment]
Okay :)
