### ISSUE TITLE
 Call to a member function isDisplayed() on null

### ISSUE THREAD

**Issue by dcblogdev** [roquie/laravel-dusk-select2#15]
First thanks for this package.

Not sure if I'm doing this correctly I have an ajax select2:

```html
<div class="form-group">
    <label for='contactId'>Contact <span class="required">*</span></label>
    <div class="form-group">
        <select id="contactSelect2" class="form-control select2Ajax clear" data-url="{{ route('admin.contacts.search') }}" data-limit="10" data-type="select" name="contactId" required>
            <option value="">Please select a Contact</option>
        </select>
    </div>
</div>
```

In my test I'm calling 

```php
->select2('#contactSelect2', 'test', 5)
```

I receive this output:

> Error: Call to a member function isDisplayed() on null

**Comment by MeerKatDev** [comment]
I have the same problem, I'm using `select[name=$name]` and it seems to work like that. But no luck with `@`

**Comment by roquie** [comment]
I'm no longer code with laravel but I have a environment to test it. Can you send me zip-archive with minimal example to reproduce the error?

**Comment by dcblogdev** [comment]
just set up a barebones Laravel 8 with select2 and Dusk and the package worked perfectly, The project I was using earlier was on Laravel 6 so I'm guessing its a compatibility problem with the older versions of Laravel.

**Comment by MeerKatDev** [comment]
@dcblogdev the selectors work as expected?

**Comment by dcblogdev** [comment]
yes using:

```php
$this->browse(function (Browser $browser) {
    $browser->visit('/')
        ->select2('#contactSelect2', 'Joe Smith')
        ->assertSee('Joe Smith')
        ->pause('1000');
});
```

this fails on my main project upgraded it to Laravel 8 there must be something conflicting somewhere.
