### ISSUE TITLE
Tests passing locally but failing in Travis

### ISSUE THREAD

**Issue by dmarcos89** [roquie/laravel-dusk-select2#5]
Hi, any idea how to work around this behavior?
Thanks

**Comment by roquie** [comment]
I think this resolve your problem
https://laravel.com/docs/5.5/dusk#running-tests-on-travis-ci

But, I recommend use Circle CI for Laravel Dusk tests and open source projects. Because he more fast and just easy configuring browsing tests.

**Comment by dmarcos89** [comment]
Hi @roquie, i am not sure what you mean with that. Been trying to make it work with many different travis.yaml files, but couldn't succeed... any other idea? or where to look?
Thanks

**Comment by roquie** [comment]
You can use Docker for running tests in browser. And then run the docker image in travis.

Concept:
https://medium.com/@yiquanzhou/run-selenium-ui-tests-in-docker-container-78be98e1b52d

Step by step:
1. Create a Dockerfile
2. Install software for browser tests.
3. Install all application dependencies
4. Copy all app flles to docker container
5. Run the "dusk's" tests when container started.

This is a basic steps. Hope this helps.
