### ISSUE TITLE
Unable to find element

### ISSUE THREAD

**Issue by longestdrive** [roquie/laravel-dusk-select2#7]
Hi. I'm new to Dusk and struggling to get Dusk to find a select2 element so thought I'd try your package

My tests though come up with this error:
```
Facebook\WebDriver\Exception\NoSuchElementException : no such element: Unable to locate element: {"method":"css selector","selector":"body [dusk="product + .select2"]"}
```
So telling me it can't find the item

I probably have done something wrong in my set up - can you help me set up correctly please.

In my form I have:
```
{{ Form::select('product', $products, NULL, array(
    'dusk'=>'product', 
    'id'=>'product', 
    'required'=>'required', 
    'class'=>'form-control select2', 
    'title'=>'select type of event being booked'
)) }}
```
In my js I have:
```
$(document).ready(function () {

            $('select').select2();
});
```
and in my test I have:
```
$browser->select2('@product', $products->first()->name);
```

What am I doing wrong?

**Comment by roquie** [comment]
Select css selector is wrong. Try `#product` like this `$browser->select2('#product', $products->first()->name);` or add class with name `product-select` to the form builder and try again like this `$browser->select2('.product-select', $products->first()->name);`.

**Comment by roquie** [comment]
Closed because there is no response.
