### ISSUE TITLE
When multiple select2 elements are on page, search field detection is unreliable

### ISSUE THREAD

**Issue by andrewmy** [roquie/laravel-dusk-select2#8]
Select2 No. 1: 10 options => has search field.
Select2 No. 2: 3 options => no search field.

The test fills out the first select2 successfully, then tries to send keys to the select2 and fails, because now the search field is not visible.

Searching for `:visible` produces weird behaviour, so now the workaround for me is to wrap the `sendKeys()` into a `try...catch` block:

```
        try {
            foreach ((array) $value as $item) {
                $element->sendKeys($item);
                sleep($wait);
                $this->click('.select2-results__option--highlighted');
            }

            return $this;
        } catch (\Exception $exception) {}
```

**Comment by roquie** [comment]
May be use the low level exception? This problem it can be reproduced by little test?

**Comment by andrewmy** [comment]
See PR #10

**Comment by roquie** [comment]
https://github.com/roquie/laravel-dusk-select2/pull/10 Merged.

https://github.com/roquie/laravel-dusk-select2/releases/tag/1.0.3
